server:
  error:
    include-message: always
    include-binding-errors: always

  port: 8080

spring:
  profiles:
    active: dev-postgres

---
spring:
  profiles: dev-postgres
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/product-catalog
    username: postgres
    password: admin

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

#  sql:
#    init:
#      mode: always
